### ISSUE TITLE
확률 관련해서 어플을 만들고 있는데 여쭙고싶은 부분이 있어 글을 남깁니다

### ISSUE THREAD

**Issue by Bue-von-hon** [philyoun/maple#1]
안녕하세요 저는 유튜브에서 넘어온 시청자입니다
안그래도 그날 스타포스는 정말 말도 안된다고 생각을 하고 있었습니다
아무튼 정말 좋은 내용의 영상이라 다시한번 감사드립니다

현재 몇퍼센트의 확률로 성공, 실패하는 아이템이 몇번만에 붙는지 대략의 범위정도를 알려주는 어플을 만들고자 하는데 아무래도 저는 전공이 CS라 확률에 대해 어떻게 접근을 해야하는지 난감했습니다

혹시 실례가 되지않는다면 통계학의 어떤 부분을 알아야 영상처럼 분석이 가능한지 도움을 받을 수 있을까 싶어 이렇게 글을 씁니다

p.s.
어떤 책을 참고하면 좋을지 알려주신다면 더할나위 없이 좋을 것 같습니다

**Comment by philyoun** [comment]
어떤 걸 상상하시는지요?
사용자가 30% 확률로 성공하는 아이템을 업그레이드 시키고 있다고 가정.

1. 몇 번만에 성공하는지 대략의 범위를 알려줌.
그럼 평균을 말씀하시는거겠죠? 
100%로 당첨되는 복권을 산다면 1번만에 당첨될 것이고, 
90%로 당첨되는 복권을 산다면 1/0.9 = 10/9번만에 당첨이 된다고 기대값을 구할 수 있을 것이고. 
30%로 당첨되는 복권을 산다면 1/0.3 = 10/3번만에 당첨이 된다고 기대값을 구할 수 있을 것이고.
왜 기대값이 1/당첨확률, 1/p이냐?
성공할 때까지 반복하는 시행횟수를 확률변수 X라고 두면, X는 기하분포(Geometric distn)를 따르고, 이 확률변수 X의 평균은 1/p이기 때문입니다.(그냥 구글검색하시면 바로 나오는 내용입니다. 어렵지 않아용 찾아보세요) 

근데 이렇게 단순하게 기대값만 딱딱 내뱉는 그런 재미없는 걸 머릿속으로 상상하시진 않았을테고, '범위'라는 걸 언급하셨으니깐..
이런 확률변수 X는 분산도 가지고 있겠죠? 구글하면 나오듯이 분산은 1/p(1-p)입니다.
30%짜리 성공확률을 가진 걸 몇 번이나 시행하는지에 대한 분산도 구할 수가 있을거고, 그걸로 신뢰구간을 만들어서 '90%의 확률로 3-12번 시도하시면 1번은 성공하실거에요!' 나 '95%의 확률로 3-12번 시도하시면 1번은 성공하실거에요!' 이런 메세지를 출력해주는 앱을 상상하신건지요?

2. 사용자가 이미 일어난 일에 대해 돌아보게 해줌
'30%짜리 성공이라고 했는데 15번이나 실패했어요ㅠㅠ'라고 했을 때 이 확률은? 15C0*(0.7)^15*(0.3)^0 = 0.0047, 
'30%짜리 성공이랬는데 15번만에 성공했어요..'라고 한다면 15C0 * (0.3)^15 + 15C1 * (0.7)^14 * 0.3 = 0.0047 + 0.0305 
첫 번째는 좀 많이 말도 안 되는 경우지만 두 번째는 못 일어날 일은 아닙니다.
뭐 이런 메세지를 출력하는 앱을 상상하시는지??

아마도 1번이겠죠?? 음..
2번은 통계입문정도에 나오는 내용이지만 1번은 수리통계학 정도에서 나오는 내용입니다. 그리고 이 경우는 모두 15성, 20성처럼 '내려가지는 않는 등급'에서의 논의이고, 다른 rank에서처럼 '떨어질수도 있는 등급'을 고려하려하면 머리를 좀 더 써봐야될거 같네요.

**Comment by Bue-von-hon** [comment]
와우…. 정말 자세하게 써주셔서 너무 감사드립니다
특히 제 구름만같던 생각을 정말 구현하려면 어떤게 필요하고 어느 부분을 좀 더 명확하게 해야하는지 감이 왔습니다
그리고 저는 말씀해주신 그 두가지에 대해서 혼용해서 생각을 하고 있었던 것 같습니다(그러니까 완전히 착각을...)
다시 한번 감사드리면서 통계입문에 나오는 내용부터 시작해서 수리통계학에 나오는 내용까지 커버하는 것을 목표로 한번 해보도록 하겠습니다

p.s.
실례되지 않는다면 어플에 해당 기능이 추가되는대로 틈틈이 연락드리겠습니다🙇🏻‍♂️🙇🏻‍♂️
아마 방학이 시작되는 7월 둘째주쯤부터 시작하면 8월초쯤에는 적당한 수준에서 간단한 기능정도는 구현이 가능할껄로 보입니다🙂
